[general]
codename = "Loki"
brand = "Mikrotik"
model = "RBwAPG-5HacD2HnD (wAP ac)"

[build]
target = "ipq40xx"
subtarget = "mikrotik"
device_profile = "mikrotik_wap-ac"

[packages]
base = [
    "curl",
    "libcurl",
    "ca-certificates",
    "lua",
    "lua-cjson",
    "luafilesystem",
    "liblua",
    "libuci-lua",
    "libubus-lua",
    # Enterprise networks
    "wpad",
    "radsecproxy",
    # OpenWISP
    "openwisp-config",
    "openwisp-monitoring",
    "netjson-monitoring",
    "openvpn-openssl",
    # Captive portal
    "opennds",
    "php8",
    "php8-cli",
    "php8-mod-openssl",
    "dnsmasq-full",
    "dnsmasq_full_dhcp",
    "dnsmasq_full_ipset",
    "ipset",
    # Wayru services
    "wayru-os-api",
    "wayru-os-services",
]